server:
  servlet:
    context-path: /cities

spring:
    main:
        banner-mode: "off"
    datasource:
        platform: h2

    freemarker:
      template-loader-path: classpath:/templates
      suffix: .ftl

logging:
    level:
        org:
            springframework: ERROR
